# Generated by Django 3.2.15 on 2022-08-20 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='quality',
            new_name='quantity',
        ),
    ]
